### ISSUE TITLE
syntax hilighting destroys  my unicode characters!

### ISSUE THREAD

**Issue by aziz** [vmg/sundown#3]
I was exited about syntax highlighting in readme files so I edited the Readme of one my gems here https://github.com/aziz/farsifu/blob/master/README.md

The code has some Persian text inside it which looks fine when editing, but the syntax highlighted version shows wierd characters! 

highlighted_image: http://cl.ly/2i2o062m0v2l1m0C2c2x

correct_form: http://cl.ly/1v2U3b2G0G073z1f3A1b

**Comment by vmg** [comment]
Thanks for the report. This is now Markdown-related however, this is an issue with the Pygments highlighter. I'll keep this open while we investigate it on detail.

**Comment by vmg** [comment]
Hey Allen,

I'm very sorry this took us so long to fix. We've just rolled out a new version of Albino that works smoothly with all kinds of Unicode characters. If you find any Unicode chars that are not yet properly rendered, that's because the old version is still on Memcached. As soon as the cache expires, it will render nicely.

Thanks again for reporting!
