### ISSUE TITLE
The name is infantile and offensive

### ISSUE THREAD

**Issue by tcumpston** [vmg/sundown#36]
If you lack the imagination to anticipate that the name will be viewed as infantile and offensive, then I assume you lack the imagination to write code that anticipates problems caused by pathological input.

**Comment by vmg** [comment]
Thank you for that piece of constructive criticism!

Unfortunately, I didn't choose the name of the library: as you can clearly see on the credits section of the README, Upskirt is a fork of an original project by Natacha Porté.

If you have any issues regarding the name of the library, you should probably contact her and demand an explanation. Make sure to remind her how _deeply_ offended you are, and possibly ask for your money back.

Cheers!

**Comment by consiliens** [comment]
"My personal distate for these particular names is heightened because it appears that the original libupskirt author's acceptance on trust of a foreign-language name for her library has caused her considerable discomfort and possibly harassment. She apparently no longer wishes to work on open source."
http://holdenweb.blogspot.com/2011/07/childish-behavior.html

**Comment by brandonc** [comment]
I think the original author's opinion, however she arrived there, is irrelevant. When a useful software project has a **marginally** offensive name, I'm left with a favorable opinion of that project because it stands in such stark contract to the tasteless commercial bullshit that pervades software.

If you actually believe that the name of this project betrays security lapses by its authors, I would be glad to direct you to any number of innocently named markdown parsers. Or perhaps that's an illogical assumption you've arrived at.

Incidently, have you petitioned the authors of 'The Gimp' to change the name of their work?

**Comment by maxbane** [comment]
Wow, that blog post and associated comments are a full-on nanny parade. Just wait until they discover the name of the Ruby bindings! (`redcarpet`, lol)

**Comment by hadley** [comment]
The name upskirt is unprofessional and misogynistic, and the binding names are worse.

**Comment by maxbane** [comment]
Chicago's new statue in Grant Park reminded me of this controversy! http://buzfairy.com/2011/07/16/marilyn-monroes-giant-statue/

**Comment by hadley** [comment]
Obviously, you (in general, not you in specific) are free to name packages however you like, it's great that you're freely contributing your time and effort to open source projects that make many people's lives easily, and it's certainly your right to think that this sort of complaint is the worst sort of politically-correct bullshit. However, to me, it seems like a good idea to avoid sexism, racism and other bigotry when possible, especially in light of the fact that programming is often considered to be an environment hostile to women.

**Comment by maxbane** [comment]
Fair enough, and I agree that some of the bindings have gone a bit too far, so as to be distasteful, and a little overenthusiastic about the whole thing. Maybe `libupskirt` is flirting with the outer bounds of taste (and who knows what Natacha's original intent was?). But really, what bothers me is that there is an important distinction between _distastefulness_ and _misogyny/sexism/bigotry_ -- the latter is (to me, anyway) a rather serious charge against somebody's moral character and substance. I think it is possible for people to do things in poor taste without necessarily thereby atainting themselves morally. When these heavy moral charges get thrown around so lightly and self-satisfyingly, it just shuts down the possibility for meaningful discussion and polarizes everybody emotionally, and the actual points of substance, like your reasonable suggestion that being distasteful in this way may have a weird interaction with some existing stereotypes about programming, get lost.

**Comment by hadley** [comment]
You make a good point. I think the danger is repeatedly pushing the bounds of taste. The occasional joke based on sexual/racial/whatever stereotypes might be fine, but consistent use of them can create a pretty nasty atmosphere, even if no one is doing it deliberately.  Maybe the reason why I feel strongly about the naming is not just upskirt, but the set of similarly themed bindings. Even redcarpet takes on an entirely different meaning in the context of the names of the other bindings.

**Comment by brandonc** [comment]
Firstly, it's traditional to name an offshoot or bindings project in the same vein as the original project name. Also, I wouldn't characterize this humor as widespread or continuous in the community otherwise the joke would have been over for me.

The only people I'm 'hostile to' are the ones that are easily offended, men or women, so quit butthurting about a project named by a woman with tasteless binding names that no one except the taste police (thought police?) cares about anyway.

**Comment by hadley** [comment]
Glad to see you're bringing in some homophobic comments to round things out.

**Comment by brandonc** [comment]
That word was used to prove how oversensitive you are.

**Comment by vmg** [comment]
Alright gentlemen, let's try to stay civil here, shall we? This is the
issue tracker of an open source project, not Slashdot. Non-programming
related discussion has no place here, specially if it involves name
calling and personal attacks.

Cut that now, or I'll have to moderate. There is nothing to discuss
regarding this fork's name. When (if) the original author decides to
rename her project, we'll do the same. Until then, this is a non-issue
for me. I do software, not politics.

On Sunday, July 17, 2011, brandonc
reply@reply.github.com
wrote:

> That word was used to prove how oversensitive you are.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tanoku/upskirt/issues/36#issuecomment-1588903

## 

Cheers,
Vicent Marti

**Comment by brandonc** [comment]
Sorry for stinking up your project site, Vicent. His issue seems to be mainly with bindings projects.
