### ISSUE TITLE
Sundown without extensions

### ISSUE THREAD

**Issue by brief** [vmg/sundown#66]
The latest sample `sundown` executable does not build with extensions. Is this intentional?

``` c
markdown = sd_markdown_new(0, 16, &callbacks, &options);
```

**Comment by vmg** [comment]
Yes, I changed this on purpose because with all extensions enabled, the generated executable doesn't pass the official Markdown test suite, and people keep opening issues about it. ;)

I'm working on adding `getopt` support to toggle extensions on the CLI, so that should fix you up if you need any specific ones.
